FROM node:20-alpine

WORKDIR /app

# Install Angular CLI as global in Container
RUN npm install -g @angular/cli

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 4200

#  use --host 0.0.0.0 and --poll to make Hot-Reload
CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "2000", "--disable-host-check"]
