version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: docker-angular-app
    ports:
      - "4200:4200"
    volumes:
      - .:/app #🔄 share code to real machine in Container 
      - /app/node_modules # Save node_modules in isolated Container
    environment:
      - CHOKIDAR_USEPOLLING=true # Help to detect file changes